# Fund Workstation

### Setting Up the Environment

In [2]:
import pandas as pd
import plotly.graph_objects as go
from src.fofproject.fund import Fund, input_monthly_returns, subset_of_funds, compare_funds
from fofproject.batch import plot_cumulative_returns, plot_fund_correlation_heatmap
from src.fofproject.mvo import minimum_variance_analysis
from src.fofproject.load import load_saved_json, init_funds, process_pdfs_in_folder, save_changes_in_fund, merge_funds

# Names of our portfolio & benchmark indices
our_portfolio = ['TAIREN','HAO','LEXINGTON','LIM','FOREST','WT LS','E20','3W GLOBAL','3W CHINA','3W HEALTHCARE','TIMEFOLIO','MONOLITH','PERSEVERANCE','NEO IVY','JH BIOTECH']
our_index = ['MSCI CHINA','TOPIX','S&P 500','MSCI WORLD', 'EUREKAHEDGE']

#### Load Data via .json

In [24]:
test = load_saved_json(folder_path=r"input")
print(type(test))
funds = init_funds(test)
print(funds['LIM JAPAN'].monthly_returns)

<class 'list'>
[{'datetime': datetime.datetime(2019, 1, 31, 0, 0), 'month': datetime.datetime(2019, 1, 1, 0, 0), 'value': 0.0062}, {'datetime': datetime.datetime(2019, 2, 28, 0, 0), 'month': datetime.datetime(2019, 2, 1, 0, 0), 'value': -0.0035}, {'datetime': datetime.datetime(2019, 3, 31, 0, 0), 'month': datetime.datetime(2019, 3, 1, 0, 0), 'value': -0.0026}, {'datetime': datetime.datetime(2019, 4, 30, 0, 0), 'month': datetime.datetime(2019, 4, 1, 0, 0), 'value': 0.0181}, {'datetime': datetime.datetime(2019, 5, 31, 0, 0), 'month': datetime.datetime(2019, 5, 1, 0, 0), 'value': 0.0031}, {'datetime': datetime.datetime(2019, 6, 30, 0, 0), 'month': datetime.datetime(2019, 6, 1, 0, 0), 'value': 0.0168}, {'datetime': datetime.datetime(2019, 7, 31, 0, 0), 'month': datetime.datetime(2019, 7, 1, 0, 0), 'value': 0.0101}, {'datetime': datetime.datetime(2019, 8, 31, 0, 0), 'month': datetime.datetime(2019, 8, 1, 0, 0), 'value': 0.0046}, {'datetime': datetime.datetime(2019, 9, 30, 0, 0), 'month': datetime.datetime(2019, 9, 1, 0, 0), 'value': 0.0071}, {'datetime': datetime.datetime(2019, 10, 31, 0, 0), 'month': datetime.datetime(2019, 10, 1, 0, 0), 'value': 0.0019}, {'datetime': datetime.datetime(2019, 11, 30, 0, 0), 'month': datetime.datetime(2019, 11, 1, 0, 0), 'value': 0.0208}, {'datetime': datetime.datetime(2019, 12, 31, 0, 0), 'month': datetime.datetime(2019, 12, 1, 0, 0), 'value': 0.0617}, {'datetime': datetime.datetime(2020, 1, 31, 0, 0), 'month': datetime.datetime(2020, 1, 1, 0, 0), 'value': 0.0004}, {'datetime': datetime.datetime(2020, 2, 29, 0, 0), 'month': datetime.datetime(2020, 2, 1, 0, 0), 'value': -0.0335}, {'datetime': datetime.datetime(2020, 3, 31, 0, 0), 'month': datetime.datetime(2020, 3, 1, 0, 0), 'value': -0.0373}, {'datetime': datetime.datetime(2020, 4, 30, 0, 0), 'month': datetime.datetime(2020, 4, 1, 0, 0), 'value': 0.0044}, {'datetime': datetime.datetime(2020, 5, 31, 0, 0), 'month': datetime.datetime(2020, 5, 1, 0, 0), 'value': 0.0241}, {'datetime': datetime.datetime(2020, 6, 30, 0, 0), 'month': datetime.datetime(2020, 6, 1, 0, 0), 'value': -0.0383}, {'datetime': datetime.datetime(2020, 7, 31, 0, 0), 'month': datetime.datetime(2020, 7, 1, 0, 0), 'value': -0.0015}, {'datetime': datetime.datetime(2020, 8, 31, 0, 0), 'month': datetime.datetime(2020, 8, 1, 0, 0), 'value': -0.0067}, {'datetime': datetime.datetime(2020, 9, 30, 0, 0), 'month': datetime.datetime(2020, 9, 1, 0, 0), 'value': 0.0261}, {'datetime': datetime.datetime(2020, 10, 31, 0, 0), 'month': datetime.datetime(2020, 10, 1, 0, 0), 'value': 0.0246}, {'datetime': datetime.datetime(2020, 11, 30, 0, 0), 'month': datetime.datetime(2020, 11, 1, 0, 0), 'value': 0.0114}, {'datetime': datetime.datetime(2020, 12, 31, 0, 0), 'month': datetime.datetime(2020, 12, 1, 0, 0), 'value': -0.0147}, {'datetime': datetime.datetime(2021, 1, 31, 0, 0), 'month': datetime.datetime(2021, 1, 1, 0, 0), 'value': -0.0042}, {'datetime': datetime.datetime(2021, 2, 28, 0, 0), 'month': datetime.datetime(2021, 2, 1, 0, 0), 'value': 0.0455}, {'datetime': datetime.datetime(2021, 3, 31, 0, 0), 'month': datetime.datetime(2021, 3, 1, 0, 0), 'value': 0.0183}, {'datetime': datetime.datetime(2021, 4, 30, 0, 0), 'month': datetime.datetime(2021, 4, 1, 0, 0), 'value': -0.0085}, {'datetime': datetime.datetime(2021, 5, 31, 0, 0), 'month': datetime.datetime(2021, 5, 1, 0, 0), 'value': 0.0113}, {'datetime': datetime.datetime(2021, 6, 30, 0, 0), 'month': datetime.datetime(2021, 6, 1, 0, 0), 'value': 0.0027}, {'datetime': datetime.datetime(2021, 7, 31, 0, 0), 'month': datetime.datetime(2021, 7, 1, 0, 0), 'value': 0.0096}, {'datetime': datetime.datetime(2021, 8, 31, 0, 0), 'month': datetime.datetime(2021, 8, 1, 0, 0), 'value': 0.0058}, {'datetime': datetime.datetime(2021, 9, 30, 0, 0), 'month': datetime.datetime(2021, 9, 1, 0, 0), 'value': 0.0189}, {'datetime': datetime.datetime(2021, 10, 31, 0, 0), 'month': datetime.datetime(2021, 10, 1, 0, 0), 'value': 0.009}, {'datetime': datetime.datetime(2021, 11, 30, 0, 0), 'month': datetime.datetime(2021, 11, 1, 0, 0), 'value': -0.0166}, {'datetime': datetime.datetime(2021, 12, 31, 0, 0), 'month': datetime.datetime(2021, 12, 1, 0, 0), 'value': 0.0259}, {'datetime': datetime.datetime(2022, 1, 31, 0, 0), 'month': datetime.datetime(2022, 1, 1, 0, 0), 'value': -0.0159}, {'datetime': datetime.datetime(2022, 2, 28, 0, 0), 'month': datetime.datetime(2022, 2, 1, 0, 0), 'value': 0.0147}, {'datetime': datetime.datetime(2022, 3, 31, 0, 0), 'month': datetime.datetime(2022, 3, 1, 0, 0), 'value': -0.0127}, {'datetime': datetime.datetime(2022, 4, 30, 0, 0), 'month': datetime.datetime(2022, 4, 1, 0, 0), 'value': 0.0032}, {'datetime': datetime.datetime(2022, 5, 31, 0, 0), 'month': datetime.datetime(2022, 5, 1, 0, 0), 'value': 0.0274}, {'datetime': datetime.datetime(2022, 6, 30, 0, 0), 'month': datetime.datetime(2022, 6, 1, 0, 0), 'value': 0.0034}, {'datetime': datetime.datetime(2022, 7, 31, 0, 0), 'month': datetime.datetime(2022, 7, 1, 0, 0), 'value': 0.0237}, {'datetime': datetime.datetime(2022, 8, 31, 0, 0), 'month': datetime.datetime(2022, 8, 1, 0, 0), 'value': 0.0117}, {'datetime': datetime.datetime(2022, 9, 30, 0, 0), 'month': datetime.datetime(2022, 9, 1, 0, 0), 'value': -0.0091}, {'datetime': datetime.datetime(2022, 10, 31, 0, 0), 'month': datetime.datetime(2022, 10, 1, 0, 0), 'value': 0.0262}, {'datetime': datetime.datetime(2022, 11, 30, 0, 0), 'month': datetime.datetime(2022, 11, 1, 0, 0), 'value': 0.0054}, {'datetime': datetime.datetime(2022, 12, 31, 0, 0), 'month': datetime.datetime(2022, 12, 1, 0, 0), 'value': 0.0034}, {'datetime': datetime.datetime(2023, 1, 31, 0, 0), 'month': datetime.datetime(2023, 1, 1, 0, 0), 'value': 0.0338}, {'datetime': datetime.datetime(2023, 2, 28, 0, 0), 'month': datetime.datetime(2023, 2, 1, 0, 0), 'value': 0.0216}, {'datetime': datetime.datetime(2023, 3, 31, 0, 0), 'month': datetime.datetime(2023, 3, 1, 0, 0), 'value': 0.0236}, {'datetime': datetime.datetime(2023, 4, 30, 0, 0), 'month': datetime.datetime(2023, 4, 1, 0, 0), 'value': 0.0328}, {'datetime': datetime.datetime(2023, 5, 31, 0, 0), 'month': datetime.datetime(2023, 5, 1, 0, 0), 'value': 0.0188}, {'datetime': datetime.datetime(2023, 6, 30, 0, 0), 'month': datetime.datetime(2023, 6, 1, 0, 0), 'value': 0.0446}, {'datetime': datetime.datetime(2023, 7, 31, 0, 0), 'month': datetime.datetime(2023, 7, 1, 0, 0), 'value': 0.0371}, {'datetime': datetime.datetime(2023, 8, 31, 0, 0), 'month': datetime.datetime(2023, 8, 1, 0, 0), 'value': 0.0133}, {'datetime': datetime.datetime(2023, 9, 30, 0, 0), 'month': datetime.datetime(2023, 9, 1, 0, 0), 'value': 0.0191}, {'datetime': datetime.datetime(2023, 10, 31, 0, 0), 'month': datetime.datetime(2023, 10, 1, 0, 0), 'value': 0.0266}, {'datetime': datetime.datetime(2023, 11, 30, 0, 0), 'month': datetime.datetime(2023, 11, 1, 0, 0), 'value': 0.0346}, {'datetime': datetime.datetime(2023, 12, 31, 0, 0), 'month': datetime.datetime(2023, 12, 1, 0, 0), 'value': -0.0115}, {'datetime': datetime.datetime(2024, 1, 31, 0, 0), 'month': datetime.datetime(2024, 1, 1, 0, 0), 'value': 0.0281}, {'datetime': datetime.datetime(2024, 2, 29, 0, 0), 'month': datetime.datetime(2024, 2, 1, 0, 0), 'value': 0.0639}, {'datetime': datetime.datetime(2024, 3, 31, 0, 0), 'month': datetime.datetime(2024, 3, 1, 0, 0), 'value': 0.0379}, {'datetime': datetime.datetime(2024, 4, 30, 0, 0), 'month': datetime.datetime(2024, 4, 1, 0, 0), 'value': 0.0281}, {'datetime': datetime.datetime(2024, 5, 31, 0, 0), 'month': datetime.datetime(2024, 5, 1, 0, 0), 'value': 0.0373}, {'datetime': datetime.datetime(2024, 6, 30, 0, 0), 'month': datetime.datetime(2024, 6, 1, 0, 0), 'value': 0.0242}, {'datetime': datetime.datetime(2024, 7, 31, 0, 0), 'month': datetime.datetime(2024, 7, 1, 0, 0), 'value': 0.0148}, {'datetime': datetime.datetime(2024, 8, 31, 0, 0), 'month': datetime.datetime(2024, 8, 1, 0, 0), 'value': -0.0042}, {'datetime': datetime.datetime(2024, 9, 30, 0, 0), 'month': datetime.datetime(2024, 9, 1, 0, 0), 'value': -0.0101}, {'datetime': datetime.datetime(2024, 10, 31, 0, 0), 'month': datetime.datetime(2024, 10, 1, 0, 0), 'value': -0.0011}, {'datetime': datetime.datetime(2024, 11, 30, 0, 0), 'month': datetime.datetime(2024, 11, 1, 0, 0), 'value': 0.0365}, {'datetime': datetime.datetime(2024, 12, 31, 0, 0), 'month': datetime.datetime(2024, 12, 1, 0, 0), 'value': 0.0222}, {'datetime': datetime.datetime(2025, 1, 31, 0, 0), 'month': datetime.datetime(2025, 1, 1, 0, 0), 'value': 0.0201}, {'datetime': datetime.datetime(2025, 2, 28, 0, 0), 'month': datetime.datetime(2025, 2, 1, 0, 0), 'value': 0.0167}, {'datetime': datetime.datetime(2025, 3, 31, 0, 0), 'month': datetime.datetime(2025, 3, 1, 0, 0), 'value': 0.0497}, {'datetime': datetime.datetime(2025, 4, 30, 0, 0), 'month': datetime.datetime(2025, 4, 1, 0, 0), 'value': 0.0405}, {'datetime': datetime.datetime(2025, 5, 31, 0, 0), 'month': datetime.datetime(2025, 5, 1, 0, 0), 'value': 0.0113}, {'datetime': datetime.datetime(2025, 6, 30, 0, 0), 'month': datetime.datetime(2025, 6, 1, 0, 0), 'value': 0.0136}, {'datetime': datetime.datetime(2025, 7, 31, 0, 0), 'month': datetime.datetime(2025, 7, 1, 0, 0), 'value': 0.0399}, {'datetime': datetime.datetime(2025, 8, 31, 0, 0), 'month': datetime.datetime(2025, 8, 1, 0, 0), 'value': 0.0455}]

#### Load Data via .csv

In [5]:
csv_fund = input_monthly_returns(r"RETURN DATA.csv")

#### GPT Input Factsheet

In [2]:
gpt_fund = process_pdfs_in_folder(folder_path=r"input",save=False)

Processing: input/Crabel.pdf
{
  "fund_name": "CRABEL",
  "fund_des": "CRABEL is a global alternative investment firm specializing in systematic, automated trading of worldwide futures and foreign exchange. The fund employs a highly diversified portfolio of short-term systematic trading strategies with a focus on low correlation and risk control. It targets an 8% annualized standard deviation with a one-day holding period for most trades. The fund is managed by experienced professionals including founder Toby Crabel and CEO Michael Pomada. Rating: 4, overall positive view due to strong systematic approach and long track record.",
  "performance": {
    "table": [
      ["Year", "01/01", "01/02", "01/03", "01/04", "01/05", "01/06", "01/07", "01/08", "01/09", "01/10", "01/11", "01/12", "Year"],
      ["2025", "-0.0065", "0.0166", "0.005", "0.0012", "-0.0184", "-0.0464", "-0.0487"],
      ["2024", "-0.0313", "0.0284", "0.0113", "0.0046", "0.0252", "-0.0029", "0.0052", "0.0264", "0.0216", "-0.0165", "0.0093", "-0.0048", "0.0773"],
      ["2023", "0.0296", "-0.0214", "0.001", "-0.0058", "0.001", "0.0089", "-0.0064", "-0.0168", "-0.0017", "-0.0185", "0.023", "0.0265", "0.0179"],
      ["2022", "-0.0055", "0.0007", "0.0478", "0.0152", "0", "0.0153", "0.0009", "-0.0064", "-0.0172", "0.0259", "-0.0167", "0.0002", "0.0599"],
      ["2021", "-0.0024", "0.0195", "-0.0067", "0.0062", "-0.0012", "-0.0024", "0.0021", "-0.0128", "0.0012", "0.0106", "-0.019", "0.0068", "0.0013"],
      ["2020", "0.0208", "-0.0098", "0.0066", "-0.0004", "-0.0006", "0.0045", "0.0014", "-0.0401", "0.0002", "-0.007", "0.0113", "0.0116", "-0.0028"],
      ["2019", "-0.0083", "-0.0244", "0.0346", "-0.0083", "-0.0172", "0.0391", "0.003", "0.0373", "-0.0099", "0.0288", "0.0083", "0.0005", "0.0838"],
      ["2018", "0.0898", "-0.0231", "0.0024", "0.0133", "0.0057", "-0.0039", "-0.008", "0.0123", "-0.0025", "0.0197", "-0.0043", "-0.0075", "0.0935"],
      ["2017", "-0.038", "-0.022", "0.0092", "-0.0103", "-0.0007", "0.0098", "0.0128", "-0.0032", "0.014", "0.0194", "-0.0181", "0.0052", "-0.0233"],
      ["2016", "0.0296", "0.0351", "0.0091", "0.0177", "0.0026", "0.0247", "0.0023", "-0.0395", "-0.0097", "-0.027", "-0.0141", "0.0196", "0.0485"],
      ["2015", "-0.0005", "-0.0022", "0.0156", "-0.0075", "0.0117", "-0.0345", "0.0103", "-0.0545", "0.0215", "0.0019", "0.0288", "0.0031", "-0.0093"],
      ["2014", "0.0674", "-0.0349", "0.0079", "-0.0214", "0.0153", "0.0086", "0.0048", "0.0117", "0.0145", "-0.0048", "0.0179", "0.0065", "0.0941"],
      ["2013", "0.0662", "0.0353", "0.0181", "0.0159", "-0.0365", "-0.0177", "-0.0289", "0.0046", "-0.0713", "0.007", "0.015", "0.0204", "0.021"],
      ["2012", "0.0198", "-0.0105", "0.0214", "-0.0028", "0.0185", "0.0062", "0.0337", "-0.0189", "0.0011", "0.0206", "0.038", "0.0163", "0.1514"],
      ["2011", "0.018", "0.0039", "-0.0146", "-0.0131", "0.024", "0.0075", "0.0025", "-0.025", "0.0279", "-0.0014", "-0.0458", "0.004", "-0.0145"],
      ["2010", "-0.0034", "0.0133", "-0.005", "0.0148", "0.0118", "-0.0051", "0.0176", "0.0315", "0.0079", "-0.0108", "-0.015", "0.035", "0.0951"],
      ["2009", "0.0274", "-0.0015", "-0.0002", "0.0106", "0.0202", "0.0053", "-0.0296", "0.0134", "-0.0066", "-0.0108", "-0.0159", "-0.0142", "-0.0034"],
      ["2008", "0.0272", "0.0052", "0.0295", "-0.0093", "0.0056", "0.0064", "0.0154", "-0.0371", "0.0475", "-0.0348", "-0.0257", "-0.0351", "-0.0095"],
      ["2007", "0.0291", "0.0304", "-0.0045", "-0.0134", "-0.027", "0.0433", "0.0647", "0.0358", "0.0212", "0.0316", "0.0398", "0.0406", "0.329"],
      ["2006", "0.0204", "0.0259", "0.0272", "0.006", "0.027", "0.0055", "0.0054", "-0.0443", "-0.0258", "0.0265", "0.0173", "-0.0072", "0.0841"],
      ["2005", "-0.0055", "0.014", "0.0079", "0.0325", "0.0196", "-0.0105", "-0.0297", "0.0172", "0.0061", "-0.0221", "0.0306", "0.006", "0.0659"],
      ["2004", "-0.0092", "0.0201", "-0.0189", "0.0225", "0.0129", "-0.0138", "0.0054", "0.0023", "0.0016", "0.0173", "0.0135", "0.0081", "0.0625"],
      ["2003", "-0.015", "0.0166", "-0.0405", "0.0187", "0.0141", "0.0275", "-0.0086", "0.0148", "0.0179", "-0.013", "0.0021", "-0.014", "0.0185"],
      ["2002", "0.0125", "-0.0236", "0.0301", "0.029", "-0.0014", "0.0714", "0.0998", "0.016", "0.0107", "-0.0389", "0.0434", "0.003", "0.2735"],
      ["2001", "0.1108", "-0.0137", "0.0425", "0.0664", "0.0527", "-0.0002", "0.0162", "-0.0073", "-0.0981", "-0.0258", "-0.018", "0.0202", "0.1383"],
      ["2000", "0.0202", "0.0599", "0.0155", "0.075", "0.0514", "0.0339", "0.0021", "0.0408", "0.0478", "-0.0844", "-0.0612", "0.0569", "0.274"],
      ["1999", "-0.0159", "-0.068", "-0.007", "0.0059", "0.0051", "-0.0244", "0.1818", "0.08", "-0.0152", "0.0255", "-0.0313", "0.0247", "0.1494"],
      ["1998", "0.0197", "0.0022", "-0.0024", "-0.0187", "-0.0665", "-0.0837", "0.3936", "0.0336", "-0.0445", "-0.0103", "0.1656"]
    ],
    "month_header": [
      "01/01",
      "01/02",
      "01/03",
      "01/04",
      "01/05",
      "01/06",
      "01/07",
      "01/08",
      "01/09",
      "01/10",
      "01/11",
      "01/12"
    ],
    "non_month_header": [
      "Year"
    ]
  },
  "investment_location": [
    "global"
  ],
  "investment_strategy": [
    "systematic",
    "futures_short_term"
  ],
  "investment_sector": "NaN",
  "manager_names": [
    "Michael Pomada",
    "Toby Crabel",
    "Steve Wisdom",
    "Grant Jaffarian"
  ],
  "manager_profiles": {
    "Michael Pomada": {
      "summary": "President and CEO, Portfolio Manager focusing on research, product development, and front office oversight.",
      "location": "Los Angeles, United States",
      "years_of_experience": 16
    },
    "Toby Crabel": {
      "summary": "Founder, Chairman, and CIO leading research and management with a focus on quantitative short-term trading.",
      "location": "Los Angeles, United States",
      "years_of_experience": 45
    },
    "Steve Wisdom": {
      "summary": "Senior Partner and Portfolio Manager responsible for leadership, management, and portfolio management.",
      "location": "Los Angeles, United States",
      "years_of_experience": 20
    },
    "Grant Jaffarian": {
      "summary": "Portfolio Manager of Crabel Advanced Trend and member of Management Committee.",
      "location": "Los Angeles, United States",
      "years_of_experience": 11
    }
  },
  "contact": {
    "name": "Lisa Martin",
    "location": "Los Angeles, United States",
    "email": "",
    "number": ""
  },
  "aum_size": 1576,
  "net_exposure": [0.08],
  "net_return": true,
  "management_fee": 0.02,
  "performance_fee": 0.3
}

#### Process Input

In [25]:
# Use csv to update json
funds = merge_funds(csv_fund, funds)

In [ ]:
for kk, entry in funds.items():
    # for monthly_dict in entry.monthly_returns:
    for k, v in entry.monthly_returns[0].items():
        if k == "month":
            print(kk)
        print(k, v)

datetime 2019-01-31 00:00:00
month 2019-01-01 00:00:00
value 0.0062
datetime 1998-03-31 00:00:00
month 1998-03-01 00:00:00
value 0.0197
datetime 2025-07-31 00:00:00
month 2025-07-01 00:00:00
value 0.0623
datetime 2007-05-31 00:00:00
month 2007-05-01 00:00:00
value 0.1099
datetime 2014-08-31 00:00:00
month 2014-08-01 00:00:00
value -0.0552
datetime 2013-01-31 00:00:00
month 2013-01-01 00:00:00
value 0.044
datetime 2019-01-31 00:00:00
month 2019-01-01 00:00:00
value 0.0062
datetime 2020-05-31 00:00:00
month 2020-05-01 00:00:00
value 0.0019
datetime 2007-06-30 00:00:00
month 2007-06-01 00:00:00
value 0.1165
datetime 2016-12-31 00:00:00
month 2016-12-01 00:00:00
value 0.0348
datetime 2016-12-31 00:00:00
month 2016-12-01 00:00:00
value 0.0197
datetime 2007-06-30 00:00:00
month 2007-06-01 00:00:00
value -0.0073
datetime 2018-01-31 00:00:00
month 2018-01-01 00:00:00
value 0.001335782
datetime 2018-01-31 00:00:00
month 2018-01-01 00:00:00
value 0.03
datetime 2017-06-30 00:00:00
month 2017-06-01 00:00:00
value 0.0
datetime 2015-02-28 00:00:00
month 2015-02-01 00:00:00
value -0.0423
datetime 2012-03-31 00:00:00
month 2012-03-01 00:00:00
value 0.0162
datetime 2021-02-28 00:00:00
month 2021-02-01 00:00:00
value -0.0739
datetime 2020-01-31 00:00:00
month 2020-01-01 00:00:00
value -0.0172
datetime 2022-02-28 00:00:00
month 2022-02-01 00:00:00
value 0.0001
datetime 2017-05-31 00:00:00
month 2017-05-01 00:00:00
value 0.0235
datetime 2023-06-30 00:00:00
month 2023-06-01 00:00:00
value 0.144
datetime 2020-01-31 00:00:00
month 2020-01-01 00:00:00
value -0.025

#### Save the Changes

In [27]:
save_changes_in_fund(funds)

🔄 Existing CSV found. Updated with new data and saved to input/returns.csv

### Compare Multiple Funds

In [5]:
for k, v in funds.items():
    print(k)
    if not v.name:
        print("found empty value")

funds['CRABEL'].name

LIM JAPAN
CRABEL
E20
TAIREN
HAO
LEXINGTON
LIM
FOREST
MSCI CHINA
TOPIX
S&P 500
MSCI WORLD
RDGFF
EUREKAHEDGE
WT LS
3W GLOBAL
3W CHINA
3W HEALTHCARE
TIMEFOLIO
MONOLITH
PERSEVERANCE
NEO IVY
JH BIOTECH

'CRABEL'

In [6]:
df = compare_funds(funds)
print(df["Name"].to_list())
df

['LIM JAPAN', 'CRABEL', 'E20', 'TAIREN', 'HAO', 'LEXINGTON', 'LIM', 'FOREST', 'MSCI CHINA', 'TOPIX', 'S&P 500', 'MSCI WORLD', 'RDGFF', 'EUREKAHEDGE', 'WT LS', '3W GLOBAL', '3W CHINA', '3W HEALTHCARE', 'TIMEFOLIO', 'MONOLITH', 'PERSEVERANCE', 'NEO IVY', 'JH BIOTECH']

,Name,Description,Location,Strategy,Sector,Managers,Contact,AUM,Net Exposure,Net Return,...,Inception Date,Latest Date,# Months,Cumulative Return,Annualized Return,Volatility,Sharpe Ratio,Sortino Ratio,Max Drawdown,Positive Months
0,LIM JAPAN,The LIM Japan Event Fund focuses on corporate ...,[apac],[activists],[equity_diversified],LIM Advisors Limited,"{'name': '', 'location': 'Hong Kong SAR', 'ema...",152.3,[0.899],True,...,2019-01-01,2025-08-01,80,1.968927,0.177308,0.070268,2.523314,6.242601,0.087128,0.775000
1,CRABEL,CRABEL is a global alternative investment firm...,[global],"[systematic, futures_short_term]",NaN,"Michael Pomada, Toby Crabel, Steve Wisdom, Gra...","{'name': 'Lisa Martin', 'location': 'Los Angel...",1576.0,[0.08],True,...,1998-03-01,2025-06-01,328,6.480199,0.076397,0.123727,0.617464,1.342092,0.162644,0.609756
2,E20,E20 Global Opportunity Investment Fund launche...,"[apac, north_america]",[equity_ls],"[equity_TMT, equity_consumer]",None,"{'name': '', 'location': 'Hong Kong', 'email':...",190.0,[0.27],False,...,NaT,NaT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TAIREN,None,None,None,None,None,None,NaN,None,None,...,2007-05-01,2025-07-01,219,31.494952,0.210150,0.175089,1.200250,2.421641,0.179276,0.671233
4,HAO,None,None,None,None,None,None,NaN,None,None,...,2014-08-01,2025-07-01,132,25.713837,0.348042,0.265242,1.312165,2.889132,0.211048,0.636364
5,LEXINGTON,None,None,None,None,None,None,NaN,None,None,...,2013-01-01,2025-07-01,151,15.547512,0.249836,0.147923,1.688957,4.527304,0.108453,0.662252
6,LIM,None,None,None,None,None,None,NaN,None,None,...,2019-01-01,2025-07-01,79,1.839720,0.171796,0.069608,2.468054,6.010626,0.087128,0.772152
7,FOREST,None,None,None,None,None,None,NaN,None,None,...,2020-05-01,2025-07-01,63,1.348594,0.176603,0.089504,1.973128,3.927223,0.088300,0.809524
8,MSCI CHINA,None,None,None,None,None,None,NaN,None,None,...,2007-06-01,2025-07-01,218,1.210135,0.044621,0.261800,0.170440,0.255297,0.648160,0.573394
9,TOPIX,None,None,None,None,None,None,NaN,None,None,...,2016-12-01,2025-07-01,104,1.453500,0.109112,0.130445,0.836456,1.324964,0.196858,0.663462
10,S&P 500,None,None,None,None,None,None,NaN,None,None,...,2016-12-01,2025-07-01,104,2.338674,0.149244,0.158604,0.940989,1.495105,0.238714,0.701923
11,MSCI WORLD,None,None,None,None,None,None,NaN,None,None,...,2007-06-01,2025-07-01,218,2.946738,0.078501,0.161691,0.485499,0.712404,0.535860,0.619266
12,RDGFF,None,None,None,None,None,None,NaN,None,None,...,2018-01-01,2025-07-01,91,1.829922,0.147030,0.102668,1.432088,3.104244,0.078768,0.681319
13,EUREKAHEDGE,None,None,None,None,None,None,NaN,None,None,...,2018-01-01,2025-07-01,91,0.448562,0.050080,0.074657,0.670802,1.118665,0.138768,0.582418
14,WT LS,None,None,None,None,None,None,NaN,None,None,...,2017-06-01,2025-07-01,98,3.616857,0.206003,0.117609,1.751601,3.828646,0.153165,0.663265
15,3W GLOBAL,None,None,None,None,None,None,NaN,None,None,...,2015-02-01,2025-07-01,126,6.133250,0.205773,0.131850,1.560659,4.566397,0.106092,0.690476
16,3W CHINA,None,None,None,None,None,None,NaN,None,None,...,2012-03-01,2025-07-01,161,3.993634,0.127343,0.074912,1.699901,3.642958,0.096000,0.689441
17,3W HEALTHCARE,None,None,None,None,None,None,NaN,None,None,...,2021-02-01,2025-07-01,54,0.036359,0.007968,0.206635,0.038561,0.052192,0.544285,0.592593
18,TIMEFOLIO,None,None,None,None,None,None,NaN,None,None,...,2020-01-01,2025-07-01,67,0.670728,0.096285,0.137785,0.698806,1.465960,0.198229,0.597015
19,MONOLITH,None,None,None,None,None,None,NaN,None,None,...,2022-02-01,2025-06-01,41,1.010667,0.226825,0.176616,1.284283,2.930144,0.133407,0.634146
20,PERSEVERANCE,None,None,None,None,None,None,NaN,None,None,...,2017-05-01,2025-07-01,99,4.980765,0.242088,0.206901,1.170069,2.202456,0.229340,0.626263
21,NEO IVY,None,None,None,None,None,None,NaN,None,None,...,2023-06-01,2025-06-01,25,0.299959,0.134191,0.179531,0.747453,1.992660,0.161676,0.480000
22,JH BIOTECH,None,None,None,None,None,None,NaN,None,None,...,2020-01-01,2025-07-01,67,4.856673,0.372429,0.236598,1.574098,3.612567,0.223271,0.686567

In [7]:
# Combine all conditions in a single filter
mask = (df["Sharpe Ratio"] > 1) & (df["Annualized Return"] > 0.1) & (df["AUM"] > 10) 

# Column List = ["Name", "Description", "Location", "Strategy", "Sector", "Managers", "Contact", "AUM", 
#                     "Net Exposure", "Net Return", "Mgmt Fee", "Perf Fee", "Inception Date", "Latest Date", 
#                     "# Months", "Cumulative Return", "Annualized Return", "Volatility", "Sharpe Ratio", 
#                     "Sortino Ratio", "Max Drawdown", "Positive Months"]

# Then, select only the columns you want
df['Worth a Look'] = mask
filtered = df[["Worth a Look","Name", "Location","Strategy", "AUM", "Sharpe Ratio", "Annualized Return", "Max Drawdown","Description"]]
filtered

,Worth a Look,Name,Location,Strategy,AUM,Sharpe Ratio,Annualized Return,Max Drawdown,Description
0,True,LIM JAPAN,[apac],[activists],152.3,2.523314,0.177308,0.087128,The LIM Japan Event Fund focuses on corporate ...
1,False,CRABEL,[global],"[systematic, futures_short_term]",1576.0,0.617464,0.076397,0.162644,CRABEL is a global alternative investment firm...
2,False,E20,"[apac, north_america]",[equity_ls],190.0,NaN,NaN,NaN,E20 Global Opportunity Investment Fund launche...
3,False,TAIREN,None,None,NaN,1.200250,0.210150,0.179276,None
4,False,HAO,None,None,NaN,1.312165,0.348042,0.211048,None
5,False,LEXINGTON,None,None,NaN,1.688957,0.249836,0.108453,None
6,False,LIM,None,None,NaN,2.468054,0.171796,0.087128,None
7,False,FOREST,None,None,NaN,1.973128,0.176603,0.088300,None
8,False,MSCI CHINA,None,None,NaN,0.170440,0.044621,0.648160,None
9,False,TOPIX,None,None,NaN,0.836456,0.109112,0.196858,None
10,False,S&P 500,None,None,NaN,0.940989,0.149244,0.238714,None
11,False,MSCI WORLD,None,None,NaN,0.485499,0.078501,0.535860,None
12,False,RDGFF,None,None,NaN,1.432088,0.147030,0.078768,None
13,False,EUREKAHEDGE,None,None,NaN,0.670802,0.050080,0.138768,None
14,False,WT LS,None,None,NaN,1.751601,0.206003,0.153165,None
15,False,3W GLOBAL,None,None,NaN,1.560659,0.205773,0.106092,None
16,False,3W CHINA,None,None,NaN,1.699901,0.127343,0.096000,None
17,False,3W HEALTHCARE,None,None,NaN,0.038561,0.007968,0.544285,None
18,False,TIMEFOLIO,None,None,NaN,0.698806,0.096285,0.198229,None
19,False,MONOLITH,None,None,NaN,1.284283,0.226825,0.133407,None
20,False,PERSEVERANCE,None,None,NaN,1.170069,0.242088,0.229340,None
21,False,NEO IVY,None,None,NaN,0.747453,0.134191,0.161676,None
22,False,JH BIOTECH,None,None,NaN,1.574098,0.372429,0.223271,None

In [ ]:
filtered.to_csv("output/funds_comparison.csv", index=False)

#### Compare Performance Table

In [30]:
funds['RDGFF'].export_monthly_table(benchmark_fund = funds['MSCI CHINA'], benchmark_name = "MSCI\nChina" ,language = "en", inception_column = True)
funds['RDGFF'].export_monthly_table(benchmark_fund = funds['MSCI WORLD'], benchmark_name = "MSCI\nWorld" ,language = "en", inception_column = True)

KeyError: 'month'

#### Plot Cumulative Return

In [8]:

funds_to_be_plot = subset_of_funds(funds, ['RDGFF', 'EUREKAHEDGE','MSCI CHINA'])
start_month = "2007-12"
end_month = "2024-7"

plot = plot_cumulative_returns(
    funds=funds_to_be_plot,
    title="",
    start_month=start_month,
    end_month=end_month,
    style="excel",
    language="en",
    blur=True,
    aspect_lock=True,
    custom_ticks=False,
    save=False,
    toggle=False
    )

### Correlation Heat Map

In [9]:
# Correlation heatmap

funds_to_be_plot = funds
start_month = "2019-12"
end_month = "2020-7"

fig, corr_df, overlap_df = plot_fund_correlation_heatmap(funds_to_be_plot, method="pearson", min_overlap=12)

### Summary of a Fund

In [28]:
funds['NEO IVY'].summary_of_a_fund(benchmark_fund=funds['MSCI CHINA'],language="en")

None
None

KeyError: 'month'

#### Quick Investigation

In [ ]:
the_fund_to_investigate = funds['RDGFF']
benchmark_fund = funds['MSCI CHINA']
# The List = ["cagr","vol","sharpe","sortino","mdd","beta","corr","win","best","worst","aum","skew","kurt","turnover"]

fig = the_fund_to_investigate.export_key_metrics_table(
            benchmark_fund=benchmark_fund,
            end_month=the_fund_to_investigate.latest_date,
            language="en",
            metrics=["cagr", "vol", "sharpe", "sortino", "mdd", "beta", "corr", "win"],
            horizontal=False,
        )