# Fund Workstation

## Pre-Analysis Loading

#### Environment Setting

In [1]:
import pandas as pd
import plotly.graph_objects as go
from src.fofproject.fund import Fund, input_monthly_returns, subset_of_funds, compare_funds
from fofproject.batch import plot_cumulative_returns, plot_fund_correlation_heatmap
from src.fofproject.mvo import minimum_variance_analysis
from src.fofproject.load import load_saved_json, init_funds, process_pdfs_in_folder, save_changes_in_fund, merge_funds, rerun_no_perf_files, continue_running

# Names of our portfolio & benchmark indices
our_portfolio = ['TAIREN','HAO','LEXINGTON','LIM','FOREST','WT CHINA','E20','3W GLOBAL','3W CHINA','3W HEALTHCARE','TIMEFOLIO','MONOLITH','PERSEVERANCE','NEO IVY','JH BIOTECH']
our_index = ['MSCI CHINA','TOPIX','S&P 500','MSCI WORLD', 'EUREKAHEDGE']

#### Load Data via .json

In [2]:
test = load_saved_json(folder_path=r"input\worth_a_look")
funds = init_funds(test)

In [3]:
port = load_saved_json(folder_path=r"input\portfolio")
port = init_funds(port)
funds = funds | port

#### Load Data via .csv

In [ ]:
# Use for manually update csv data and merge with json file 
csv_fund = input_monthly_returns(r"RETURN DATA.csv")

#### GPT Input Factsheet

##### Parse Everything

In [3]:
# Do not open the pdf while running, or the renaming process will encounter error
gpt_fund = process_pdfs_in_folder(folder_path=r"input\sg_ms_manager",save=True)
gpt_fund = init_funds(gpt_fund)

Processing: input\sg_ms_manager\06aec2928c814318840ba5f6dfc4c70a.pdf
Processing: input\sg_ms_manager\08eb10b4f5984ea995e84c65e7f68a88.pdf
Processing: input\sg_ms_manager\0df5a8b4bfab4481b76cfffc062a43ce.pdf
Processing: input\sg_ms_manager\15c92ddabd3d4c97b4c5699771c6e7cc.pdf
Wrongly assigned a month header of 8 from GOKU TECHNOLOGIES, would result in extra values in earliest and latest months
Processing: input\sg_ms_manager\1e629e7cdab1497aabea1b9ffe3b8afe.pdf
Processing: input\sg_ms_manager\2292539676b64484b8472f64f0c33e13.pdf
Processing: input\sg_ms_manager\2c8533dc86054d588d73d7e1f76cded0.pdf
Processing: input\sg_ms_manager\2df14967a2774714a068d76d474b1ef0.pdf
Wrongly assigned a month header of 0 from SORA, would result in extra values in earliest and latest months
Empty values in performance table of SORA
Processing: input\sg_ms_manager\2e358c049c124209882425840ef86a2d.pdf
Processing: input\sg_ms_manager\30c7f3f760c54e188ebb4c2ffa07c52e.pdf
Only one year 2025 found in table of MONOLITH, returned empty list
Processing: input\sg_ms_manager\30d6572bd49e4257a21461b7c67840e1.pdf
Wrongly assigned a month header of 0 from PERMIAN, would result in extra values in earliest and latest months
Empty values in performance table of PERMIAN
Processing: input\sg_ms_manager\426c28508be048d0bdcadbe65c9550df.pdf
Processing: input\sg_ms_manager\46cc7b9f108045d8bbc4f4feda54578c.pdf
Processing: input\sg_ms_manager\4afc3be25a2b49f7b7e1d9ce2d07c14c.pdf
Processing: input\sg_ms_manager\4f15a3517dba42398b387f8acf3d65ef.pdf
Processing: input\sg_ms_manager\520fff867acc4457adf5dcf39877032f.pdf
Processing: input\sg_ms_manager\52b71e3c957e43d8ab81713cca987fe5.pdf
Processing: input\sg_ms_manager\52bd4bc9bcee4308bd44a5f709d76d9e.pdf
Processing: input\sg_ms_manager\56e1f2dc92e7443c974f565bae157cec.pdf
Processing: input\sg_ms_manager\57bc9e40bb02411ab99313232b55bf76.pdf
Processing: input\sg_ms_manager\6359644ca4b5451f82499dc34d26a876.pdf
Wrongly assigned a month header of 0 from ARROWPOINT, would result in extra values in earliest and latest months
Empty values in performance table of ARROWPOINT
Processing: input\sg_ms_manager\65f7a7ad1f8744cf9ab368710875aab7.pdf
Processing: input\sg_ms_manager\68155b34c6664d3d87fec0685b2daf18.pdf
Processing: input\sg_ms_manager\6b1d1b4c9d6a4ee089b4b2bf774aac9f.pdf
Processing: input\sg_ms_manager\6b549cc39fdc4b38b28b6c0c5be9ca65.pdf
Processing: input\sg_ms_manager\706b60b6e0da416f817416b7b8e47ac0.pdf
Processing: input\sg_ms_manager\707080d52a004a73a5ddf9006da88bf1.pdf
Wrongly assigned a month header of 0 from TOROA, would result in extra values in earliest and latest months
Empty values in performance table of TOROA
Processing: input\sg_ms_manager\7410354c03e942a0aeb8dd8b2015187a.pdf
Processing: input\sg_ms_manager\7beac1c619e9412fa9bef2ba053f3a5c.pdf
Processing: input\sg_ms_manager\7c098bd6a08d4400a2e70b55854f4dbc.pdf
Processing: input\sg_ms_manager\7e677c9da5434a6394e1a0d6a6cab94a.pdf
Processing: input\sg_ms_manager\809159df6b8a43a186dd4321934036ca.pdf
Processing: input\sg_ms_manager\92f670d8fb0146ed961d8c02e826fead.pdf
Processing: input\sg_ms_manager\94e3aa167da74b789670b8e5b103c6ef.pdf
Processing: input\sg_ms_manager\955fcead83094275a1e75c77de46d6e6.pdf
Processing: input\sg_ms_manager\9653cf10d3d2454f8e16c68b9f188ff6.pdf
Processing: input\sg_ms_manager\97399e79b04b416d8a732247c40865a7.pdf
Processing: input\sg_ms_manager\98d81753217146429c684b709fbcad63.pdf
Processing: input\sg_ms_manager\98f0d9cf296b4149901ecb4f252646aa.pdf
Processing: input\sg_ms_manager\9d323c73649d402d85dc98fd9761a95a.pdf
Processing: input\sg_ms_manager\9dc1d334a43c436abd5c2283e6d639c0.pdf
Processing: input\sg_ms_manager\9dd0ff8d8c5442baa9c28f4eac62873a.pdf
Processing: input\sg_ms_manager\a2b071f7ab6545adbbe0fcffbec81b21.pdf
Processing: input\sg_ms_manager\a362b451b04342c1bb8eb184555ccf57.pdf
Processing: input\sg_ms_manager\a55c463d85dc400e9112bfe434eb04c6.pdf
Processing: input\sg_ms_manager\af1ccc147a1941a0992788bbb4413af6.pdf
Processing: input\sg_ms_manager\bd9ef678c86744a78bf4e6a133374179.pdf
Processing: input\sg_ms_manager\c2fbae0dd3c944239201a5ecc78c3c84.pdf
Processing: input\sg_ms_manager\c8ee1de4ef9642e3bd03a6cb5e40cfd7.pdf
Only one year 2025 found in table of KEYSTONE, returned empty list
Processing: input\sg_ms_manager\c95431141b4e4ada97a19a90fea2f47a.pdf
Processing: input\sg_ms_manager\ca729a845c754fe089d3330a10f538e8.pdf
Processing: input\sg_ms_manager\cf59c266bb934275bbbb858ed5451ad0.pdf
Processing: input\sg_ms_manager\d1328bd3a86b4b0ca0035146464358d5.pdf
Processing: input\sg_ms_manager\e0077f6dbdb74b4289da0fe38efbcb9b.pdf
Processing: input\sg_ms_manager\e14d7b0ed34c458683d1f8673a62ff48.pdf
Wrongly assigned a month header of 0 from POLYMER JAPAN, would result in extra values in earliest and latest months
Empty values in performance table of POLYMER JAPAN
Processing: input\sg_ms_manager\f4109ca4a54843deb37dd6541b6e2aee.pdf

##### Continue Running Unparsed

In [2]:
gpt_fund_2 = continue_running(folder_path=r"input\less_compelling",save=True)
gpt_fund_2 = init_funds(gpt_fund_2)

Processing: input\less_compelling\ENGADINE_EU_EquityLS_less than 1 Sharpe.pdf
Processing: input\less_compelling\FINEPOINT_ASIA_Eventdriven_5% rtn.pdf
Processing: input\less_compelling\FORT_NA_Event driven_7.8%rtn.pdf
Processing: input\less_compelling\G2_US_TMT specialist_less than 1 sharpe.pdf
Processing: input\less_compelling\GCM Grosvenor_US_EquityLS_7% rtn.pdf
Processing: input\less_compelling\GMO_US_EquityLS_18%vol.pdf
Processing: input\less_compelling\GOLDENTREE_NY_Credit_9.7% rtn.pdf
Processing: input\less_compelling\GREENHOUSE_US_EquityLS_less than 1 Sharpe.pdf
Processing: input\less_compelling\GREENVALE_Global_Market Neutral_less than 1 Sharpe.pdf
Processing: input\less_compelling\HIGHBRIDGE_Global_Multi-strat_8% rtn 5% vol.pdf
Processing: input\less_compelling\HIGHGROUND_Global_EquityLS_less than 1 sharpe.pdf
Processing: input\less_compelling\ICW_Global_Long only_9% rtn.pdf
Processing: input\less_compelling\ISHANA_China&India_Fundamental_19% vol.pdf
Processing: input\less_compelling\KATAMARAN_Global_EquityLS_6.8% rtn.pdf
Processing: input\less_compelling\LAKEWOOD_NA_EquityLS_less than 1 sharpe.pdf
Processing: input\less_compelling\LIGHTSTREET_Global_EquityLS_19% vol.pdf
Processing: input\less_compelling\LOCUST_NA_Directional_ less than 1 Sharpe.pdf
Processing: input\less_compelling\MACHINA NEUTRON_EU_EquityLS_8% rtn.pdf
Processing: input\less_compelling\MAN Group_Global_Multi-strat_7.2% rtn.pdf
Processing: input\less_compelling\MASSAR_Global_Relative Value_less than 1 Sharpe.pdf
Processing: input\less_compelling\MAVERICK_Global_EquityLS_less than 1 Sharpe.pdf
Processing: input\less_compelling\METAVASI_Global_TMT Specialist_16% vol.pdf
Processing: input\less_compelling\MLM_Global_Macro_17% vol.pdf
Processing: input\less_compelling\MOLECULE_Global_Multi-strat_Around 1 Sharpe.pdf
Processing: input\less_compelling\MULTI-ASSET_Global_Long only(Quant)_less than 1 Sharpe.pdf
Processing: input\less_compelling\NIPUN_ASIA_Market Neutral(Quant)_less than 1 Sharpe.pdf
Processing: input\less_compelling\NITORUM_NA_Fundamental_less than 1 sharpe.pdf
Processing: input\less_compelling\NORTHREEF_NA_Market Neutral_16.6% rtn 8.2% vol.pdf
Processing: input\less_compelling\OVATA_ASIA_Multi-strat_less than 1 sharpe.pdf
Processing: input\less_compelling\OWL CREEK_Global_Event driven_Less than 1 Sharpe.pdf
Processing: input\less_compelling\PARK PRESIDIO_US_Fundamental_less than 1 Sharep.pdf
Processing: input\less_compelling\PARSIFAL_Global_EquityLS_less than 1 Sharpe.pdf
Processing: input\less_compelling\PERRYRIDGE_Global_Fundamental_less than 1 Sharpe.pdf
Processing: input\less_compelling\PERTENTO_Global_EquityLS_around 1 Sharpe.pdf
Processing: input\less_compelling\PINNBROOK_Global_Macro_less than 1 Sharpe.pdf
Processing: input\less_compelling\QMS_Global_Quant Macro_less than 1 Sharpe.pdf
Processing: input\less_compelling\Quantica_Global_CTA_less than 1 Sharpe.pdf
Processing: input\less_compelling\RBC_EM_Credit_around 1 Sharpe.pdf
Processing: input\less_compelling\ROW_Global_Quant Macro_4% rtn.pdf
Processing: input\less_compelling\SAGIL_LA_EquityLS_less than 1 Sharpe.pdf
Processing: input\less_compelling\SATURN_US_healthcare specialist_less than 1 sharpe.pdf
Processing: input\less_compelling\SCGE_Global_TMT focused_Less than 1 Sharpe.pdf
Processing: input\less_compelling\SCOPIA_Global+EquityLS_less than 1 Sharpe.pdf
Processing: input\less_compelling\SENVEST_Global_EquityLS_30% vol.pdf
Processing: input\less_compelling\SINO_Taiwan_Market Neutral_9% rtn.pdf
Processing: input\less_compelling\SPHERA_Middle East_EquityLS_around 1 sharpe.pdf
Processing: input\less_compelling\STANDARD INVESTMENT_NA_Energy specialist_less than 1 sharpe.pdf
Processing: input\less_compelling\STEADFAST_NA_Fundamental_less than 1 sharpe.pdf
Processing: input\less_compelling\STEELMILL_Global_Macro_less than 1 sharpe.pdf
Processing: input\less_compelling\STONY_US_TMT Specialist_less than 1 sharpe.pdf
Processing: input\less_compelling\SUNRIVER_NA_EquityLS_less than 1 sharpe.pdf
Processing: input\less_compelling\TACTICAL_Global_EquityLS(Quant)_less than 1 sharpe.pdf
Processing: input\less_compelling\TAIGA_Nordic_EquityLS_around 1 sharpe.pdf
Processing: input\less_compelling\THIRDPOINT_Global_Multi-Strat_around 1 sharpe.pdf
Processing: input\less_compelling\THORNETREE_Global_TMT Specialist_less than 1 Sharpe.pdf
Processing: input\less_compelling\TREXQUANT_NA_Statistical Arb_around 1 Sharpe.pdf
Processing: input\less_compelling\TWOTAIL_Global_Niche_0.16% Sharpe.pdf
Processing: input\less_compelling\VOYAGER_Global_Long only_less than 1 sharpe.pdf
Processing: input\less_compelling\WELLINGTON_TMT Specialist_less than 1 Sharpe.pdf
Processing: input\less_compelling\WOODSON_TMT Specialist_less than 1 Sharpe.pdf

In [ ]:
gpt_fund = gpt_fund_2 | gpt_fund

##### Re-Run No Performance Funds

In [ ]:
# Target the files with "No Performance Found", and re-run the analysis again
rerun_no_perf_files(folder_path=r"input\worth_a_look",save=True)

#### Merging Different Input

In [ ]:
# Use the left hand's PERFORMANCE TABLE to update the right hand one
funds = merge_funds(csv_fund, funds)

In [ ]:
# Right-hand side has higher priority
funds = funds | funds

#### Save the Changes to .json & .csv

In [4]:
# Careful what fund you are saving to what folder
save_changes_in_fund(funds, folder_path=r"input\worth_a_look")

⚠️ Skipping GLOBAL OPPORTUNITIES (no performance data).
⚠️ Skipping PALOMA (no performance data).
⚠️ Skipping VAR AI (no performance data).
🔄 Existing CSV found. Updated with new data and saved to input\worth_a_look\returns.csv

{'3W CHINA': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=162 entries),
 '3W GLOBAL': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=127 entries),
 '3W HEALTHCARE': Fund(performance_fee=0.15, management_fee=0.015, monthly_returns=55 entries),
 'APEX': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=63 entries),
 'ARVIN': Fund(performance_fee=0.15, management_fee=0.015, monthly_returns=49 entries),
 'ASIAN ALPHA': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=34 entries),
 'BWCP': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=66 entries),
 'CALIGAN': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=42 entries),
 'CARTENNA CAPITAL': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=63 entries),
 'CENTIVA': Fund(performance_fee=0.2, management_fee=0, monthly_returns=100 entries),
 'CFM CUMULUS': Fund(performance_fee=0.15, management_fee=0.01, monthly_returns=18 entries),
 'DIADEMA': Fund(performance_fee=0.2, management_fee=0.0175, monthly_returns=12 entries),
 'E20': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=2 entries),
 'EGERTON': Fund(performance_fee=0.15, management_fee=0.01, monthly_returns=367 entries),
 'ENGINE CAPITAL': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=144 entries),
 'EUREKAHEDGE': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=92 entries),
 'FOREST': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=64 entries),
 'GLOBAL OPPORTUNITIES': Fund(performance_fee=0.25, management_fee=0.0025, monthly_returns=0 entries),
 'HAO': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=133 entries),
 'HELIUM': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=20 entries),
 'HIDDENITE': Fund(performance_fee=0.125, management_fee=0.015, monthly_returns=58 entries),
 'JH BIOTECH': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=68 entries),
 'KAPITALO': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=86 entries),
 'KATHMANDU': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=82 entries),
 'LEXINGTON': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=152 entries),
 'LIM': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=80 entries),
 'MOAT CAPITAL': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=108 entries),
 'MONOLITH': Fund(performance_fee=0.15, management_fee=0.015, monthly_returns=43 entries),
 'MSCI CHINA': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=219 entries),
 'MSCI WORLD': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=219 entries),
 'MULTI-ALPHA': Fund(performance_fee=0.15, management_fee=0.01, monthly_returns=114 entries),
 'NEO IVY': Fund(performance_fee=0.15, management_fee=0.015, monthly_returns=27 entries),
 'NISA CONFLUENCE': Fund(performance_fee=0.15, management_fee=0.01, monthly_returns=34 entries),
 'PALOMA': Fund(performance_fee=0, management_fee=0.015, monthly_returns=0 entries),
 'PENSO MACRO': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=10 entries),
 'PERSEVERANCE': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=100 entries),
 'POLAR MULTI-STRATEGY': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=402 entries),
 'PROEM': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=77 entries),
 'RDGFF': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=91 entries),
 'RIVERMONT': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=52 entries),
 'RTW': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=184 entries),
 'RUBRIC CAPITAL': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=105 entries),
 'S&P 500': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=105 entries),
 'SAND GROVE': Fund(performance_fee=0.175, management_fee=0.015, monthly_returns=126 entries),
 'SCULPTOR': Fund(performance_fee=0.2, management_fee=0.0175, monthly_returns=378 entries),
 'SELIGMAN HEALTHCARE': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=24 entries),
 'SHAOLIN CAPITAL': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=100 entries),
 'SOLEUS CAPITAL': Fund(performance_fee=0.2, management_fee=0.0175, monthly_returns=82 entries),
 'TACTICAL ALPHA': Fund(performance_fee=0.125, management_fee=0.0125, monthly_returns=50 entries),
 'TAIREN': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=220 entries),
 'TCIM': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=145 entries),
 'THINK INVESTMENTS': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=138 entries),
 'TIMEFOLIO': Fund(performance_fee=0.2, management_fee=0.015, monthly_returns=68 entries),
 'TOPIX': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=105 entries),
 'VAR AI': Fund(performance_fee=0.2, management_fee=0.01, monthly_returns=0 entries),
 'VELLICHOR': Fund(performance_fee=0.15, management_fee=0.0125, monthly_returns=13 entries),
 'WHG GLOBAL': Fund(performance_fee=0.15, management_fee=0.015, monthly_returns=51 entries),
 'WINDWARD': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=42 entries),
 'WOLF HILL': Fund(performance_fee=0.2, management_fee=0.0175, monthly_returns=100 entries),
 'WT CHINA': Fund(performance_fee=0.2, management_fee=0.02, monthly_returns=99 entries)}

In [ ]:
print(funds['ASIAN TECHNOLOGY'].total_max_dd)

## Fund Analysis

#### Dataframe Comparison

In [5]:
df = compare_funds(funds)
do_not_display = our_index + our_portfolio
df = df[~df["Name"].isin(do_not_display)].reset_index(drop=True)
df.head(3)

,Name,Description,Location,Strategy,Sector,Managers,Contact,AUM (in Mn USD),Net Exposure,Net Return,...,Latest Date,Month Running,# Months,Cumulative Return,Annualized Return,Volatility,Sharpe Ratio,Sortino Ratio,Max Drawdown,Positive Months
0,APEX,"APEX is a systematic, multi-strategy hedge fun...",[global],"[systematic, multi-strat]",equity_diversified,"Jorge Fernandez Cuervo, Cameron McElroy","Jorge Fernandez Cuervo - Based in LONDON, UNIT...",4283.0,Net Exposure = 0% to 0%,True,...,2025-06-01,62.900000,63,1.452383,0.186335,0.087386,2.132319,4.723199,0.061645,0.730159
1,ARVIN,ARVIN is a hedge fund focused on equity long/s...,"[north_america, global]","[equity_ls, special_situation]","[equity_consumer, equity_industrials, equity_T...","Rohan Varavadekar, Christopher Bonanni","Rohan Varavadekar - Based in Austin, Texas, Un...",508.0,Net Exposure = 30.0% to 65.0%,True,...,2025-06-01,48.700000,49,0.686744,0.136590,0.103109,1.324715,3.031259,0.084283,0.673469
2,ASIAN ALPHA,ASIAN ALPHA is an equity long/short hedge fund...,[apac],[equity_ls],[equity_diversified],"Andrew Alexander, Raymond Chan, Patrick Cheung...","Andrew Alexander - Based in Hong Kong, try rea...",72.0,Net Exposure = -10.0% to 10.0%,True,...,2025-06-01,33.466667,34,0.522823,0.160017,0.056688,2.822794,10.099125,0.023961,0.794118

In [ ]:
# Column List = ["Name", "Description", "Location", "Strategy", "Sector", "Managers", "Contact", "AUM (in Mn USD)", 
#                     "Net Exposure", "Net Return", "Mgmt Fee", "Perf Fee", "Inception Date", "Latest Date", "Month Running",
#                     "# Months", "Cumulative Return", "Annualized Return", "Volatility", "Sharpe Ratio", 
#                     "Sortino Ratio", "Max Drawdown", "Positive Months"]

In [6]:
# sort by what we think important   
df = df.sort_values(by=["Sharpe Ratio", "Annualized Return"], ascending=[False, False])
# mask and filtered only the wanted funds
mask = (df["AUM (in Mn USD)"] > 100) & (df["Month Running"] > 12) & (df["Annualized Return"] > 0.14)
df['Worth a Look'] = mask
# Display only the following columns
display_df = df[["Worth a Look","Name", "Sharpe Ratio", "Annualized Return", "AUM (in Mn USD)", "Month Running","Description","Max Drawdown" ]]
display_df

,Worth a Look,Name,Sharpe Ratio,Annualized Return,AUM (in Mn USD),Month Running,Description,Max Drawdown
2,False,ASIAN ALPHA,2.822794,0.160017,72.0,33.466667,ASIAN ALPHA is an equity long/short hedge fund...,0.023961
29,True,SELIGMAN HEALTHCARE,2.454964,0.203775,132.8,23.366667,The Seligman Healthcare Spectrum Strategy is a...,0.034927
17,True,MULTI-ALPHA,2.285885,0.171239,1041.2,114.633333,MULTI-ALPHA OPPORTUNITY is a global macro mult...,0.053596
6,False,CENTIVA,2.239032,0.066554,2840.0,100.466667,"CENTIVA is a diversified, absolute return orie...",0.027108
12,False,HELIUM,2.227511,0.148626,43.0,19.266667,HELIUM GLOBAL EVENT DRIVEN FUND is an event dr...,0.039600
8,False,DIADEMA,2.177811,0.074286,68.0,11.166667,DIADEMA is an equity long/short fund focused o...,0.007000
5,False,CARTENNA CAPITAL,2.159765,0.114787,147.7,62.900000,Cartenna Capital is a long/short equity hedge ...,0.040000
14,False,KAPITALO,2.142192,0.139036,3260.0,86.266667,KAPITALO K10 is a global macro and commodities...,0.037252
0,True,APEX,2.132319,0.186335,4283.0,62.900000,"APEX is a systematic, multi-strategy hedge fun...",0.061645
7,False,CFM CUMULUS,1.970277,0.129916,637.4,17.233333,CFM Cumulus is a multi-strategy absolute retur...,0.025634
20,False,PENSO MACRO,1.886198,0.188911,0.0,9.166667,"PENSO MACRO CONVEXITY is a discretionary, mult...",0.036659
16,False,MOAT CAPITAL,1.838170,0.129166,562.0,108.566667,MOAT CAPITAL EQUITY HEDGE is a market neutral ...,0.053300
36,False,VELLICHOR,1.823445,0.268514,0.0,12.166667,Vellichor is a fundamentally driven equity lon...,0.042100
32,False,TACTICAL ALPHA,1.726769,0.080469,1549.0,49.733333,TACTICAL ALPHA is a multi-strategy hedge fund ...,0.038035
28,False,SCULPTOR,1.689304,0.103725,8694.0,382.466667,SCULPTOR is a global multi-strategy hedge fund...,0.180142
18,False,NISA CONFLUENCE,1.560373,0.101614,0.0,33.466667,NISA Confluence Fund is a multi-strategy hedge...,0.046800
13,True,HIDDENITE,1.516158,0.355296,235.0,57.800000,HIDDENITE CAPITAL PARTNERS LP is a fundamental...,0.224143
23,False,RDGFF,1.432088,0.147030,NaN,91.266667,None,0.078768
21,False,POLAR MULTI-STRATEGY,1.397638,0.120414,4591.2,406.833333,Polar Multi-Strategy Fund is a hedge fund mana...,0.432146
4,True,CALIGAN,1.386867,0.270257,370.0,41.566667,"Caligan is a concentrated, long-biased hedge f...",0.161700
33,False,TCIM,1.383114,0.128322,1201.0,146.100000,TCIM is a global equity long/short hedge fund ...,0.148813
1,False,ARVIN,1.324715,0.136590,508.0,48.700000,ARVIN is a hedge fund focused on equity long/s...,0.084283
15,False,KATHMANDU,1.321611,0.138145,23.0,82.166667,KATHMANDU is a global long/short equity strate...,0.068069
24,True,RIVERMONT,1.306471,0.146402,285.0,51.766667,Rivermont is a New York-based hedge fund launc...,0.112047
9,False,EGERTON,1.282883,0.131627,2388.0,371.333333,EGERTON LONG-SHORT MASTER FUND LIMITED is a he...,0.292703
27,False,SAND GROVE,1.264472,0.096859,1000.0,126.800000,SAND GROVE MERGER ARB STRATEGY is a European f...,0.100400
31,True,SOLEUS CAPITAL,1.204298,0.187551,1500.0,82.166667,SOLEUS CAPITAL is a healthcare-focused equity ...,0.167737
38,True,WINDWARD,1.109387,0.239562,136.0,41.566667,WINDWARD is an equity long/short hedge fund fo...,0.117630
3,False,BWCP,1.108258,0.127442,142.0,65.933333,"BWCP is a fundamentally based, concentrated eq...",0.179130
10,True,ENGINE CAPITAL,1.099722,0.144903,886.0,145.100000,ENGINE CAPITAL is a long-biased value-oriented...,0.192529
26,True,RUBRIC CAPITAL,1.092171,0.198281,2947.0,105.500000,Rubric Capital is a deep value equity long/sho...,0.180862
34,True,THINK INVESTMENTS,1.090009,0.159474,2645.0,138.966667,Think Investments is a global equity long/shor...,0.225029
30,False,SHAOLIN CAPITAL,1.087746,0.099409,1000.0,100.466667,SHAOLIN CAPITAL is a hedge fund launched in 20...,0.109183
39,True,WOLF HILL,1.020417,0.216548,1018.0,100.466667,WOLF HILL is a hedge fund focused on North Ame...,0.156273
37,True,WHG GLOBAL,0.992009,0.153895,360.0,50.733333,WHG GLOBAL LONG BIASED is a global equity long...,0.159053
22,True,PROEM,0.954941,0.197637,376.0,77.066667,PROEM is a long/short equity fund focused on g...,0.390639
25,True,RTW,0.826284,0.181993,2900.0,185.700000,RTW is a healthcare-focused equity long/short ...,0.391680
11,False,GLOBAL OPPORTUNITIES,NaN,NaN,180.0,NaN,Global Opportunities is a global multi-strateg...,NaN
19,False,PALOMA,NaN,NaN,1390.9,NaN,PALOMA is a multi-strategy hedge fund focused ...,NaN
35,False,VAR AI,NaN,NaN,1000.0,NaN,VAR AI FUND is a fundamental-focused hedge fun...,NaN

#### Save it to CSV

In [ ]:
# Select the column you want to save
output_df = df[["Worth a Look","Name", "Sharpe Ratio", "Annualized Return", "AUM (in Mn USD)", "Month Running","Max Drawdown" ,"Net Exposure","Strategy", "Sector","Contact","Description", "Mgmt Fee", "Perf Fee"]]
output_df.to_csv("output/funds_comparison.csv", index=False)

#### Save it to a list

In [11]:
exclude_list = our_index + our_portfolio
df = df[~df["Name"].isin(exclude_list)].reset_index(drop=True)
worth_looking = df.loc[df["Worth a Look"], "Name"].tolist()
print(worth_looking)

['SELIGMAN HEALTHCARE', 'MULTI-ALPHA', 'APEX', 'HIDDENITE', 'CALIGAN', 'RIVERMONT', 'SOLEUS CAPITAL', 'WINDWARD', 'ENGINE CAPITAL', 'RUBRIC CAPITAL', 'THINK INVESTMENTS', 'WOLF HILL', 'WHG GLOBAL', 'PROEM', 'RTW']

#### Compare Performance Table

In [ ]:
funds['RDGFF'].export_monthly_table(benchmark_fund = funds['MSCI CHINA'], benchmark_name = "MSCI\nChina" ,language = "en", inception_column = True)

#### Plot Cumulative Return

In [13]:

funds_to_be_plot = subset_of_funds(funds, ['RDGFF','MSCI CHINA','EUREKAHEDGE'])
start_month = "2015-12"
end_month = "2025-7"

plot = plot_cumulative_returns(
    funds=funds_to_be_plot,
    title="",
    start_month=start_month,
    end_month=end_month,
    style="excel",
    language="en",
    blur=False,
    aspect_lock=True,
    custom_ticks=False,
    save=False,
    toggle=False
    )

#### Correlation Heat Map

In [ ]:
# Correlation heatmap
list_to_plot = our_portfolio + ['BASSWOOD']
print(list_to_plot)
funds_to_be_plot = subset_of_funds(funds, list_to_plot)
start_month = "2019-12"
end_month = "2025-7"

fig, corr_df, overlap_df = plot_fund_correlation_heatmap(funds_to_be_plot, method="pearson", min_overlap=12)

#### Efficient Frontier Analysis

In [ ]:
minimum_variance_analysis(funds)

(Figure({
     'data': [{'hovertemplate': '<b>%{x}</b><br>weight = %{y:.2%}<extra></extra>',
               'marker': {'color': 'rgba(193,174,148,0.75)', 'line': {'color': '#C1AE94', 'width': 1.0}},
               'type': 'bar',
               'x': array(['RDGFF', 'MSCI CHINA', 'EUREKAHEDGE'], dtype=object),
               'y': array([0.31387902, 0.        , 0.68612098])}],
     'layout': {'font': {'color': '#53565A', 'family': 'Montserrat, Roboto', 'size': 14},
                'margin': {'b': 60, 'l': 60, 'r': 40, 't': 80},
                'template': '...',
                'title': {'text': '<b>Global Minimum-Variance Portfolio</b>', 'x': 0.5, 'xanchor': 'center'},
                'xaxis': {'showgrid': False, 'tickangle': 45},
                'yaxis': {'tickformat': '.0%', 'title': {'text': 'Weight'}}}
 }),
 RDGFF          0.313879
 MSCI CHINA     0.000000
 EUREKAHEDGE    0.686121
 dtype: float64,
 {'n_months': 91,
  'ann_vol': np.float64(0.06520713792963775),
  'ann_ret': 0.08027608003064922,
  'cov':                 RDGFF  MSCI CHINA  EUREKAHEDGE
  RDGFF        0.000878    0.000239     0.000115
  MSCI CHINA   0.000239    0.005491     0.001253
  EUREKAHEDGE  0.000115    0.001253     0.000464,
  'mu': RDGFF          0.011923
  MSCI CHINA     0.003185
  EUREKAHEDGE    0.004296
  dtype: float64,
  'used_returns':                RDGFF  MSCI CHINA  EUREKAHEDGE
  2018-01-01  0.001336      0.1255       0.0300
  2018-02-01  0.016258     -0.0636      -0.0154
  2018-03-01  0.016598     -0.0301      -0.0107
  2018-04-01  0.011936     -0.0003      -0.0014
  2018-05-01  0.007835      0.0181       0.0104
  ...              ...         ...          ...
  2025-03-01 -0.003130      0.0202      -0.0006
  2025-04-01  0.008220     -0.0455       0.0014
  2025-05-01 -0.003669      0.0391       0.0235
  2025-06-01  0.019984      0.0386       0.0219
  2025-07-01  0.026542      0.0484       0.0202

  [91 rows x 3 columns]})

#### Summary of a Fund

In [ ]:
funds['ARVIN'].summary_of_a_fund(benchmark_fund=funds['MSCI CHINA'],language="en")

#### Quick Investigation

In [ ]:
the_fund_to_investigate = funds['RDGFF']
benchmark_fund = funds['MSCI CHINA']
# The List = ["cagr","vol","sharpe","sortino","mdd","beta","corr","win","best","worst","aum","skew","kurt","turnover"]

fig = the_fund_to_investigate.export_key_metrics_table(
            benchmark_fund=benchmark_fund,
            end_month=the_fund_to_investigate.latest_date,
            language="en",
            metrics=["cagr", "vol", "sharpe", "sortino", "mdd", "beta", "corr", "win"],
            horizontal=False,
        )